# Generated by Django 3.2.1 on 2021-06-04 11:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Mobile number must contain 10 digits', regex='^\\d{10}$')], verbose_name='Mobile number'),
        ),
    ]
