# Generated by Django 3.2.1 on 2021-07-22 10:19

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(blank=True, default='avatars/no_image.jpg', upload_to=apps.accounts.models.avatar_directory_path, verbose_name='Photo'),
        ),
    ]
