version: '3.8'
services:

#########
# REDIS #
#########

#   redis:
#     restart: always
#     image: "redis:4-alpine"
#     ports:
#       - "6379:6379"
#     network_mode: host

############
# FRONTEND #
############

#   nginx:
#     restart: always
#     image: "nginx:1"
#     container_name: endlessproject_nginx_1
#     ports:
#       - "80:80"
#       - "443:443"
#     env_file:
#       - ./.env_defaults
#       - ./.env
#     volumes:
#       - /home/ubuntu/endless_project/var/www/static/:/app/static/
#       - /home/ubuntu/endless_project/var/www/media:/app/media/
#       - /home/ubuntu/endless_project/webui-app/dist/:/app/webui/
#       - /home/ubuntu/endless_project/conf/docker/nginx.conf:/etc/nginx/conf.d/default.conf
#       - /etc/letsencrypt:/etc/letsencrypt
#     network_mode: host

###########
# BACKEND #
###########

  acmon_back:
    restart: always
    build: .
    image: acmon_back
    # image: &img kozlyuk/acmon:acmon_back_latest
    container_name: acmon_back
    ports:
      - "8000:8000"
    # command: ['gunicorn', '--bind', '0.0.0.0:8000', 'appart.wsgi:application',
    #   '--worker-tmp-dir', '/dev/shm', '--workers', '2',
    #   '--threads', '4', '--worker-class', 'gthread']
    command: ['python', 'manage.py', 'runserver']
    network_mode: host
    env_file:
      - .env
    entrypoint: ['/home/app/entrypoint.sh']

##############
# IOT SERVER #
##############

  acmon_iot:
    restart: always
    # build: ../iot-python-server/
    image: kozlyuk/acmon:acmon_iot_latest
    container_name: acmon_iot
    ports:
      - "12900:12900"
    command: ['python', '-u', '/home/app/server.py']
    network_mode: host
    env_file:
      - .env

##########
# CELERY #
##########

#   celery:
#     image: *img
#     container_name: r3sourcer_celery
#     command: celery worker -n worker.celery -E -A r3sourcer -l info --scheduler=redbeat.RedBeatScheduler -Q celery,sms,hr
#     depends_on:
#       - redis
#       - clickhouse
#       - rabbitmq
#     env_file:
#       - ./.env_defaults
#       - ./.env
#     networks:
#       r3-network:
#         ipv4_address: 192.168.100.7

###############
# CELERY BEAT #
###############

#   celery-beat:
#     image: *img
#     container_name: r3sourcer_celery_beat
#     command: celery beat -A r3sourcer -l info --scheduler=redbeat.RedBeatScheduler
#     depends_on:
#       - redis
#       - clickhouse
#       - rabbitmq
#     env_file:
#       - ./.env_defaults
#       - ./.env
#     networks:
#       r3-network:
#         ipv4_address: 192.168.100.8
