# Generated by Django 3.2.1 on 2021-07-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveSmallIntegerField(unique=True, verbose_name='Code')),
                ('name', models.CharField(max_length=64, verbose_name='Property Name')),
                ('bytes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Bytes')),
                ('type', models.CharField(max_length=16, verbose_name='Type')),
                ('min_value', models.IntegerField(blank=True, null=True, verbose_name='Minimal Value')),
                ('max_value', models.IntegerField(blank=True, null=True, verbose_name='Maximal Value')),
                ('multiplier', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Multiplier')),
                ('units', models.CharField(blank=True, max_length=16, null=True, verbose_name='Units')),
                ('description', models.TextField(verbose_name='Description')),
                ('hw_support', models.TextField(verbose_name='Hardware Support')),
                ('group', models.CharField(max_length=64, verbose_name='Parameter Group')),
            ],
            options={
                'verbose_name': 'Parameter',
                'verbose_name_plural': 'Parameters',
            },
        ),
    ]
