# Generated by Django 3.2.1 on 2021-07-30 09:27
from django.core.management import CommandError
from django.db import migrations


class Migration(migrations.Migration):

    def load_parameters_from_fixture(apps, schema_editor):
        from django.core.management import call_command
        call_command("loaddata", "parameters")

    def delete_parameters(apps, schema_editor):
        Parameter = apps.get_model("devices", "Parameter")
        Parameter.objects.all().delete()


    dependencies = [
        ('devices', '0001_initial'),
    ]


    operations = [
        migrations.RunPython(load_parameters_from_fixture,
                             delete_parameters),
    ]
