# Generated by Django 3.2.1 on 2021-06-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='year_of_production',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Year of production'),
        ),
    ]
