# Generated by Django 3.2.1 on 2021-09-05 12:17

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='track_color',
            field=colorfield.fields.ColorField(default='#0000FF', max_length=18, verbose_name='Route color'),
        ),
    ]
