# Generated by Django 3.2.1 on 2021-06-04 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_model_year_of_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='car.department', verbose_name='Department'),
            preserve_default=False,
        ),
    ]
