# Generated by Django 3.2.1 on 2021-09-06 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_track_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='around_distance',
            field=models.FloatField(default=0.1, verbose_name='Around distance'),
        ),
        migrations.AddField(
            model_name='department',
            name='base_latitude',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(900000000)], verbose_name='Base latitude'),
        ),
        migrations.AddField(
            model_name='department',
            name='base_longitude',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(900000000)], verbose_name='Base longitude'),
        ),
        migrations.AddField(
            model_name='department',
            name='insignificant_distance',
            field=models.FloatField(default=10, verbose_name='Insignificant distance'),
        ),
    ]
