# Generated by Django 3.2.1 on 2021-06-03 09:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('start_time', models.DateTimeField(verbose_name='Start time')),
                ('finsh_time', models.DateTimeField(verbose_name='Finish time')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='Car')),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('timestamp', models.DateTimeField(verbose_name='Timestamp')),
                ('priority', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2)], verbose_name='Priority')),
                ('longitude', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(900000000)], verbose_name='Longitude')),
                ('latitude', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(900000000)], verbose_name='Latitude')),
                ('altitude', models.PositiveSmallIntegerField(verbose_name='Altitude')),
                ('angle', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(360)], verbose_name='Angle')),
                ('satellites', models.PositiveSmallIntegerField(verbose_name='Satelites')),
                ('speed', models.PositiveSmallIntegerField(default=0, verbose_name='Speed')),
                ('request_data', models.BinaryField(blank=True, null=True, verbose_name='Request data')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='Car')),
            ],
            options={
                'verbose_name': 'Record',
                'verbose_name_plural': 'Records',
            },
        ),
    ]
