# Generated by Django 3.2.1 on 2021-06-04 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_record_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='department',
        ),
    ]
