# Generated by Django 3.2.1 on 2021-06-16 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20210616_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='angle',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(360)], verbose_name='Angle'),
        ),
    ]
