# Generated by Django 3.2.1 on 2021-06-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_alter_record_angle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='request_data',
        ),
    ]
