# Generated by Django 3.2.1 on 2021-06-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_remove_record_request_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'get_latest_by': 'timestamp', 'verbose_name': 'Record', 'verbose_name_plural': 'Records'},
        ),
        migrations.AlterField(
            model_name='record',
            name='io_elements',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='IO Elements'),
        ),
    ]
