# Generated by Django 3.2.1 on 2021-07-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_auto_20210616_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='is_parked',
            field=models.BooleanField(default=False, verbose_name='Is parked'),
        ),
    ]
