# Generated by Django 3.2.1 on 2021-09-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_record_is_parked'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'get_latest_by': 'finish_time', 'verbose_name': 'Trip', 'verbose_name_plural': 'Trips'},
        ),
        migrations.RenameField(
            model_name='trip',
            old_name='finsh_time',
            new_name='finish_time',
        ),
        migrations.AddField(
            model_name='trip',
            name='distance',
            field=models.FloatField(default=0, verbose_name='Distance'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
    ]
