# Generated by Django 3.2.1 on 2021-09-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_auto_20210907_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='avg_speed',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Average speed'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='max_speed',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Maximum speed'),
            preserve_default=False,
        ),
    ]
