# Generated by Django 3.2.1 on 2021-09-29 12:13

import apps.tracking.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_auto_20210916_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='json_file',
            field=models.FileField(blank=True, null=True, upload_to=apps.tracking.models.car_directory_path, verbose_name='JSON file'),
        ),
    ]
